### ISSUE TITLE
Unable to install via pip or poetry

### ISSUE THREAD

**Issue by ramakanthdorai** [SpinQTech/SpinQKit#2]
I'm not able to find the package spinqkit (0.0.3)

Can you help me with this?

**Comment by SpinQTech** [comment]
May I know the OS and Python version you use?

**Comment by SpinQTech** [comment]
> I'm not able to find the package spinqkit (0.0.3)
> 
> Can you help me with this?

Please notice that SpinQKit is only available for Python 3.8 and 3.9.
